### ISSUE TITLE
module name mangling makes it difficult to import

### ISSUE THREAD

**Issue by philiparvidsson** [hylang/hy#1199] opened 2017-01-17 10:58 UTC
(import a-b) does not work when having a module named a-b.hy, which seems like a perfectly reasonable naming scheme for source files. Instead, Hy attempts to import a_b and fails with an `ImportError`(No module named a_b). I believe two attempts should be made in this case since both naming conventions make sense.

**Comment by Kodiologist** [comment] 2017-01-17 13:44
> a module named a-b.hy, which seems like a perfectly reasonable naming scheme for source files.

I disagree. Such a file can't be imported from Python with a regular `import` statement. So you should name your Hy files with underscores, even if you like to import them with hyphens.

Hence, in my view, this is not a bug.

**Comment by Kodiologist** [comment] 2017-01-26 07:12
If there are no objections, I'll close this.

**Closed by Kodiologist** 2017-01-26 07:12 UTC
