### ISSUE TITLE
Trouble importing lxml with pypy

### ISSUE THREAD

**Issue by rcarmo** [hylang/hy#832] opened 2015-06-29 10:57 UTC
I'm having trouble importing `lxml.etree` [here](https://github.com/rcarmo/sushy/blob/master/sushy/render.hy#L4), with the following results:

<pre>
Traceback (most recent call last):
  File "<builtin>/app_main.py", line 75, in run_toplevel
  File "/Users/rcarmo/.pyenv/versions/pypy-2.6.0/bin/hy", line 9, in <module>
    load_entry_point('hy==0.11.0', 'console_scripts', 'hy')()
  File "/Users/rcarmo/.pyenv/versions/pypy-2.6.0/site-packages/hy/cmdline.py", line 347, in hy_main
    sys.exit(cmdline_handler("hy", sys.argv))
  File "/Users/rcarmo/.pyenv/versions/pypy-2.6.0/site-packages/hy/cmdline.py", line 321, in cmdline_handler
    return run_module(options.mod)
  File "/Users/rcarmo/.pyenv/versions/pypy-2.6.0/site-packages/hy/cmdline.py", line 200, in run_module
    return run_file(pth)
  File "/Users/rcarmo/.pyenv/versions/pypy-2.6.0/site-packages/hy/cmdline.py", line 210, in run_file
    import_file_to_module("__main__", filename)
  File "/Users/rcarmo/.pyenv/versions/pypy-2.6.0/site-packages/hy/importer.py", line 78, in import_file_to_module
    eval(ast_compile(_ast, fpath, "exec"), mod.__dict__)
  File "/Users/rcarmo/Dropbox/Development/sushy/sushy/indexer.hy", line 1, in <module>
    (import
  File "/Users/rcarmo/.pyenv/versions/pypy-2.6.0/site-packages/hy/importer.py", line 180, in load_module
    self.path)
  File "/Users/rcarmo/.pyenv/versions/pypy-2.6.0/site-packages/hy/importer.py", line 78, in import_file_to_module
    eval(ast_compile(_ast, fpath, "exec"), mod.__dict__)
  File "/Users/rcarmo/Dropbox/Development/sushy/sushy/render.hy", line 1, in <module>
    (import
  File "lxml.etree.pyx", line 1, in init lxml.etree (src/lxml/lxml.etree.c:201852)
KeyError: '__builtins__'
</pre>

I'm using `pyenv` to run PyPY 2.6 on Mac OS X, but have similar trouble under Ubuntu with PyPy 2.5, so it should be easy to reproduce.

**Comment by zackmdavis** [comment] 2015-06-30 04:35
Does lxml.etree work for you in PyPy without Hy? (I don't have time for a detailed investigation, but at a glance, the Python 2.7 docs [mention that](https://docs.python.org/2/library/__builtin__.html) the existence of `__builtins__` is implementation-specific, and there [are](http://stackoverflow.com/a/27687603) [some](https://bugs.launchpad.net/lxml/+bug/1273709) [reports](https://bitbucket.org/pypy/compatibility/wiki/lxml) of people having trouble getting lxml to work with PyPy.)

**Comment by rcarmo** [comment] 2015-06-30 14:41
Yes, it does:

<pre>
$ python
Python 2.7.9 (295ee98b6928, May 31 2015, 07:28:49)
[PyPy 2.6.0 with GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>> from lxml.etree import Element, tostring, fromstring
>>>>
</pre>

I suspect there's something more going on here. Maybe `ast_compile` strips something away?

**Comment by zackmdavis** [comment] 2015-07-12 00:07
I couldn't reproduce with PyPy 2.6.0 on Ubuntu Trusty.
```
(hypypy2)zmd@ExpectedReturn:~/Code/Misc/hypypy2/hy$ python
Python 2.7.9 (295ee98b6928, May 31 2015, 07:29:04)
[PyPy 2.6.0 with GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> from lxml.etree import Element, tostring, fromstring
>>>> 
(hypypy2)zmd@ExpectedReturn:~/Code/Misc/hypypy2/hy$ hy
hy 0.11.0 using PyPy(295ee98b6928) 2.7.9 on Linux
=> (import [lxml.etree [Element tostring fromstring]])
=> (tostring (Element "hello-xml-parsing-world"))
'<hello-xml-parsing-world/>'
```

**Comment by Kodiologist** [comment] 2016-12-09 20:27
`(import lxml.etree)` works for me, too, with PyPy 5.4.1+dfsg-1 on Ubuntu 16.10. I'm closing the issue.

**Closed by Kodiologist** 2016-12-09 20:27 UTC
