### ISSUE TITLE
`get` raises `name not defined` with toolz library.

### ISSUE THREAD

**Issue by ekaschalk** [hylang/hy#1292] opened 2017-05-16 21:32 UTC
Toolz is a functional programming library that mimics clojure API and is useful in conjuction with hy's library. Toolz functions `curry` and `flip` fail on `hy.get`. Consider:

```
(import [toolz.curried :as tz])

((tz.curry coll? [1 2 3]))
>>> True

((tz.curry inc) 1)
>>> 2

((tz.flip isinstance bool) "hi")
>>> False

((tz.flip get 1) [0 1 2])
>>> NameError: name 'get' is not defined

((tz.curry get [0 1 2]) 1)
>>> NameError: name 'get' is not defined

((tz.curry tz.get 1) [0 1 2])  ; tz.get is reversed hy.get
>>> 1

```

The error occurs on some (but not all) other hy builtins as well:

```
((tz.curry in 0) [1 2 3])
>>> NameError: name 'in' is not defined

((tz.curry is 0) [1 2 3])
>>> NameError: name 'is' is not defined

((tz.curry last [1 2 3]))
>>> 3
```

**Comment by gilch** [comment] 2017-05-16 21:46
`get` is a *special form* that translates to Python subscript notation (i.e. `(get foo 42) ;>>> foo[42]`) not a function. This means you can't map over a collection with it, or pass it as an argument. We could possibly *shadow* it with a real function like we do with operators. If you run the Hy repl with the `hy --spy` option, you can see the equivalent Python to the AST Hy is generating.

In the meantime, you can define something like this: 
```Hy
=> (defn my-get [coll key] (get coll key))
def my_get(coll, key):
    return coll[key]
None
=> ((tz.flip my-get 1) [0 1 2])
tz.flip(my_get, 1)([0, 1, 2])
1
```

**Comment by gilch** [comment] 2017-05-16 21:54
The above is the general process for making a function out of a special form, but it turns out that Python's standard library already has this in its `operator` module.
```
=> (import [operator [getitem]])
from operator import getitem
None
=> ((tz.flip getitem 1) [0 1 2])
tz.flip(getitem, 1)([0, 1, 2])
1
```
This makes me think that `get` should be shadowed like our other operators.

**Comment by Kodiologist** [comment] 2017-05-16 22:58
Duplicate of #683.

**Closed** 2017-05-16 23:00 UTC
