### ISSUE TITLE
Macro-expansion breaks tracebacks

### ISSUE THREAD

**Issue by svetlyak40wt** [hylang/hy#980] opened 2015-10-24 07:49 UTC
When I have code, where some macro was expanded and in the code after expansion an exception was riased, line numbers in resulting traceback get corrupted.

I've created a [separate repository to simulate this problem](https://github.com/svetlyak40wt/hy-macros-problem). Don't understand how to write a unittest for it.

Here is such traceback:

```
The Header
Do something useful here
TheFooter
Traceback (most recent call last):
File "env/bin/hy", line 9, in <module>
load_entry_point('hy==0.11.0', 'console_scripts', 'hy')()
File "/Users/art/projects/test-hy-macros-problem/env/lib/python3.5/site-packages/hy/cmdline.py", line 347, in hy_main
sys.exit(cmdline_handler("hy", sys.argv))
File "/Users/art/projects/test-hy-macros-problem/env/lib/python3.5/site-packages/hy/cmdline.py", line 335, in cmdline_handler
return run_file(options.args[0])
File "/Users/art/projects/test-hy-macros-problem/env/lib/python3.5/site-packages/hy/cmdline.py", line 210, in run_file
import_file_to_module("__main__", filename)
File "/Users/art/projects/test-hy-macros-problem/env/lib/python3.5/site-packages/hy/importer.py", line 78, in import_file_to_m\
odule
eval(ast_compile(_ast, fpath, "exec"), mod.__dict__)
File "check.hy", line 14, in <module>
(foo)
File "check.hy", line 268, in foo
ZeroDivisionError: division by zero
```

The problem is in the line before the last line: `File "check.hy", line 268, in foo`.
File `check.hy` is much shorter and have no line `268`. Information about a place where exception was raised is completely lost.

That is the main reason, why I can't use HyLang in any serious project :(

**Comment by Foxboron** [comment] 2015-10-24 12:28
I'm actually working a little bit on this problem these days. We are well aware of the problem tho \o/ Thanks for the code, just what i need!

**Comment by kirbyfan64** [comment] 2015-10-24 14:39
Related to #742. I created [a shell script](https://gist.github.com/kirbyfan64/7c8a2a65552108c76b7c) that, given the invalid line number and the file name, returns the correct line number. That way you can still use Hy.

I keep feeling like this is a CPython issue, since it never happens under PyPy.

**Comment by svetlyak40wt** [comment] 2016-01-15 07:35
By the way, I've checked under pypy 4.0.1 and hy 0.11.1, the problem is similar though line numbers are not:

```
The Header
Do something useful here
TheFooter
Traceback (most recent call last):
  File "/Users/art/projects/hy-macros-problem/pypy-env/bin/hy", line 9, in <module>
    load_entry_point('hy==0.11.1', 'console_scripts', 'hy')()
  File "/Users/art/projects/hy-macros-problem/pypy-env/site-packages/hy/cmdline.py", line 347, in hy_main
    sys.exit(cmdline_handler("hy", sys.argv))
  File "/Users/art/projects/hy-macros-problem/pypy-env/site-packages/hy/cmdline.py", line 335, in cmdline_handler
    return run_file(options.args[0])
  File "/Users/art/projects/hy-macros-problem/pypy-env/site-packages/hy/cmdline.py", line 210, in run_file
    import_file_to_module("__main__", filename)
  File "/Users/art/projects/hy-macros-problem/pypy-env/site-packages/hy/importer.py", line 78, in import_file_to_module
    eval(ast_compile(_ast, fpath, "exec"), mod.__dict__)
  File "check.hy", line 1, in <module>
    (defmacro run-section [header body footer]
  File "check.hy", line 1, in foo
    (defmacro run-section [header body footer]
ZeroDivisionError: long division or modulo by zero
```

**Comment by svetlyak40wt** [comment] 2016-01-15 07:37
The same for pypy3 2.4.0:

```
The Header
Do something useful here
TheFooter
Traceback (most recent call last):
  File "/Users/art/projects/hy-macros-problem/pypy3-env/bin/hy", line 9, in <module>
    load_entry_point('hy==0.11.1', 'console_scripts', 'hy')()
  File "/Users/art/projects/hy-macros-problem/pypy3-env/site-packages/hy/cmdline.py", line 347, in hy_main
    sys.exit(cmdline_handler("hy", sys.argv))
  File "/Users/art/projects/hy-macros-problem/pypy3-env/site-packages/hy/cmdline.py", line 335, in cmdline_handler
    return run_file(options.args[0])
  File "/Users/art/projects/hy-macros-problem/pypy3-env/site-packages/hy/cmdline.py", line 210, in run_file
    import_file_to_module("__main__", filename)
  File "/Users/art/projects/hy-macros-problem/pypy3-env/site-packages/hy/importer.py", line 78, in import_file_to_module
    eval(ast_compile(_ast, fpath, "exec"), mod.__dict__)
  File "check.hy", line 1, in <module>
    (defmacro run-section [header body footer]
  File "check.hy", line 1, in foo
    (defmacro run-section [header body footer]
ZeroDivisionError: division by zero
```

**Comment by svetlyak40wt** [comment] 2016-01-15 07:37
@kirbyfan64 you said this never heppened on PyPy for you. Which version of pypy are you using?

**Comment by kirbyfan64** [comment] 2016-01-15 15:39
Yeah, that's because Hy currently sets all the line numbers under PyPy to line 1. Try commenting out lines 2611-2614 of `hy/compiler.py`, and you'll see what I mean.

**Comment by svetlyak40wt** [comment] 2016-05-11 21:58
Checked today how it works now. I've installed HyLang from fb9a97a7e5310eac1ae356d2571287b25832f949 commit.

Seems, everything is fine now under PyPy 2.4.0, 4.0.1 and 5.0.1.

But it still broken for CPython 3.5.1 and 2.7.10.

**Comment by kirbyfan64** [comment] 2016-05-12 00:15
Yeah, I really think this could potentially be a CPython issue. Again, see #742.

**Comment by kirbyfan64** [comment] 2016-05-13 19:25
Closing as duplicate of #742.

**Closed by kirbyfan64** 2016-05-13 19:25 UTC
