### ISSUE TITLE
NameError: name '//' is not defined

### ISSUE THREAD

**Issue by Zabolekar** [hylang/hy#1234] opened 2017-02-24 00:43 UTC
Currently, `(// 5 2)` is allowed but `(map // [5] [2])` raises NameError (tested with Python 3.6 only).

As far as I can see, there is no `//` function in hy.core.shadow. Would it have the same definition as `/` (the only difference being `operator.floordiv` instead of `operator.truediv` and the docstring) or am I missing something important?

**Comment by Kodiologist** [comment] 2017-02-24 00:47
Duplicate of #1103.

> Would it have the same definition as / (the only difference being `operator.floordiv` instead of `operator.truediv` and the docstring)

I believe so.

**Closed by Kodiologist** 2017-02-24 00:47 UTC
