### ISSUE TITLE
I suggest C4 for contribution process.

### ISSUE THREAD

**Issue by crocket** [hylang/hy#1716] opened 2018-12-27 04:22 UTC
[C4](https://rfc.zeromq.org/spec:42/C4/) is good for growing a community. It is focused on growing a community. It helps a project survive for longer. If you want to see C4 in action, visit https://github.com/zeromq/libzmq/pulls

http://hintjens.com/blog:106 explains the rationale behind C4.

**Comment by kirbyfan64** [comment] 2018-12-27 05:17
...why though? The main bottleneck with Hy is pretty much solely lack of developer time, and I don't see how adopting a contribution process that would have to be read by new contributors (which would increase the barrier anyway) would be beneficial. This project is a lot smaller than ZeroMQ is...

**Comment by crocket** [comment] 2018-12-27 05:34
@kirbyfan64 If you read https://github.com/zeromq/libzmq/pulls, you would realize that pull requests that abide by a few rules get merged quickly. On the contrary, https://github.com/hylang/hy/pulls tells a different story. hy doesn't have criteria for merging pull requests, and it is slow to merge pull requests.

The lesson is that the faster you merge pull requests, the bigger a community grows by attracting contributors. Contributors are more likely to come back to a project that merges pull requests quickly.

**Comment by Kodiologist** [comment] 2018-12-27 12:33
I think C4 and the blog post in question are advocating different practices. C4 says "A patch MUST compile cleanly and pass project self-tests on at least the principal target platform" whereas Hintjens's post says "I recommend to merge quickly, without waiting for Continuous Integration testing to finish". So which is being recommended here, automatic unconditional merges, or quick merges of C4's idea of a "correct patch"?

**Comment by crocket** [comment] 2018-12-27 12:47
C4 accommodates Pieter Hintjen's experiences after writing that blog article.

He realized that there needs to be rules for merging in order to avoid arguments and avoid breaking public API.

http://hintjens.com/blog:117#toc40 explains the updated story.

**Comment by Kodiologist** [comment] 2018-12-27 12:55
I see. So while PRs are expected to pass the existing tests, they're otherwise supposed to be merged, and problems should be fixed (including, presumably, reverting the whole patch) through a new PR instead of editing the old one in place. I can see the logic to that, but what do we do in the case of Wikipedia-style edit wars where person 1 submits a PR, person 2 undoes that PR, person 1 undoes the undoing, and so on?

**Comment by crocket** [comment] 2018-12-27 13:11
http://hintjens.com/blog:106 says

> PM: we get a flamewar which troll wins by sheer force of argument. Community explodes in fight-or-flee emotions. Bad patches get pushed through. OM: existing contributor immediately reverts the patch. There is no discussion. Troll may try again, and eventually may be banned. Toxic patches remain in git history forever.

C4 states

> Administrators SHOULD block or ban "bad actors" who cause stress and pain to others in the project. This should be done after public discussion, with a chance for all parties to speak. A bad actor is someone who repeatedly ignores the rules and culture of the project, who is needlessly argumentative or hostile, or who is offensive, and who is unable to self-correct their behavior when asked to do so by others.

On http://hintjens.com/blog:106, Pieter Hintjens wrote in one of his comments

> I've contributed often to Wikipedia, as a newbie, and sometimes experienced this yet not always. It depends on the page. Some pages are hostile, like some open source projects.
If a project is hostile, it makes no difference what rules you offer: those in power will be aggressive and offensive. The solution then is to fork the project and be a better owner. This is hard on Wikipedia because you can only have one page for a topic. For open source it's trivial.
I think the rules we develop (like C4, the umbrella contract we use) are more to help the majority of decent people work together than to educate abusive people into behaving.
So in practice what you describe happens, yes, yet not because of OM. A precondition for successful OM is decent owners who want their projects to grow.
Which is what we see in practice: many ZeroMQ projects practice this, and it works nicely, delivers stable growth and happiness. (And we do not see patch wars.)

I think there's a small chance that a patch war can potentially happen in a huge project like chromium web browser. If a patch war happens, someone will be banned, or someone will lose interest or leave in anger.

**Comment by Kodiologist** [comment] 2018-12-27 13:54
My concern isn't trolls who are pushing outright terrible commits. We haven't had that problem (yet?). My concern is legitimate disagreements, where I for one wouldn't be comfortable with banning either participant, especially given that, in a project this small, every contributor is precious.

The Wikipedia policy is that in a situation of clear good-faith disagreement, the page should be left as-is until a consensus is reached. That, I think, would make sense. Maybe the end result of such a policy would be little different from the status quo, but it's worth a shot, at least.

It's interesting to note the rule "Maintainers SHOULD NOT merge their own patches except in exceptional cases, such as non-responsiveness from other Maintainers for an extended period (more than 1-2 days)." Hy is much slower than ZeroMQ. Non-responsiveness from maintainers (other than the author of the PR) is the norm for much longer than 2 days. Half the reason I pushed for #1508 was that I was making PRs that got no response of any sort for months. Now that we have the two-week rule, uncontroversial PRs can at least be merged after two weeks.

**Comment by crocket** [comment] 2018-12-27 14:05
If there are two disagreeing decent people, they can compromise. I make compromises with coworkers at work, too.

Also, zeromq developers haven't seen patch wars, yet.

**Comment by alphapapa** [comment] 2018-12-27 14:09
What extant problem in the Hy project is imposing the "Collective Code Construction Contract" intended to solve?

**Comment by crocket** [comment] 2018-12-27 14:12
I can't impose C4 on Hy. I'm not a code contributor. But, I can contribute in other ways.

But, I think people will get more satisfaction from C4 or something similar to it.

Pull requests will be merged in time when maintainers have no time to review details of pull requests.
C4 can help reduce workload for maintainers.

**Comment by alphapapa** [comment] 2018-12-27 14:17
> Pull requests will be merged in time when maintainers have no time to review details of pull requests.

What is "in time"?

This is a language, not an app or even a library.  PRs *shouldn't* be merged until they have been thoroughly reviewed by the project maintainers.

> C4 can help reduce workload for maintainers.

It can also *increase* workload when the maintainers have to revert patches that shouldn't have been merged in the first place.

What are you trying to optimize for here?  Stability?  Longevity?  Features?  PR average-time-to-merge?  Maintainer workload?  You can't optimize for all of them at the same time, because some of them negatively affect others.

I will ask again, since you didn't answer it: What extant problem in the Hy project is imposing the "Collective Code Construction Contract" intended to solve?

**Comment by crocket** [comment] 2018-12-27 14:20
I see that pull requests are held up for months. It doesn't help with maintaining community size. It helps with growing community.

@alphapapa Notice that you have a strong opinion about this project, too. And, you think you are not imposing your opinion on Hy.

**Comment by alphapapa** [comment] 2018-12-27 14:31
> Notice that you have a strong opinion about this project, too. 

No, only about attempts at "drive-by" policy impositions, which seem all too common on GitHub.

> And, you think you are not imposing your opinion on Hy. 

Unlike you, I am not trying to convince Hy to adopt a lengthy, formal policy which would govern the maintainers' own actions.

> I also noticed that I couldn't find your commits in Hy project.

Indeed, I am not a Hy contributor, merely an interested bystander.  Maybe I can save the Hy maintainers a little time by raising some objections before they wander by.

**Comment by kirbyfan64** [comment] 2018-12-27 18:21
> When people learn that their contributions are delayed for months and years, they will leave.

We already have policies in place for this. This is usually the person's own lack of time, and our contributor's don't really have enough time to go through fixing/reverting everything. 

I understand stuff like this has merit, but I just think we aren't at the size or even PR count where that's even necessary, and the last thing we need is to have merged code that doesn't work.

**Comment by crocket** [comment] 2018-12-27 21:41
@kirbyfan64 C4 is not needed beyond a certain size. It is not needed. But, I think it helps.

Your concerns are addressed on

* http://hintjens.com/blog:106
* http://hintjens.com/blog:117#toc40

**Comment by alphapapa** [comment] 2018-12-27 22:00
> Reading just my comments is not sufficient to understand the lessons of the past.

Perhaps it would help if you compared and contrasted ZeroMQ with Hy, explaining why you think that what's best for ZeroMQ is also what's best for Hy.

**Comment by crocket** [comment] 2018-12-27 22:05
Those articles explain better than I can. The best way to understand the lessons of the past is to read those articles and take a few minutes to observe zeromq pull requests. Whether or not you adopt C4, it is educational.

**Comment by alphapapa** [comment] 2018-12-27 22:11
Lessons of the past?  Let's look at a few examples of the "problems" caused by non-C4 processes:

> It tells new contributors, "guilty until proven innocent," which is a negative message that creates negative emotions. 

That's just silly.

> It gives maintainers power over new contributors, which many maintainers abuse. This abuse can be subconscious. Yet it is widespread. Maintainers inherently strive to remain important in their project. If they can keep out potential competitors by delaying and blocking their patches, they will.

Also silly.  If a maintainer is being so abusive, fork the project.  We're talking about FOSS.

> It opens the door to discrimination. One can argue, a project belongs to its maintainers, so they can choose who they want to work with. My response is: projects that are not aggressively inclusive will die, and deserve to die.

See previous.  If you don't like how the project is run, fork it.  Let the better project win.

> It slows down the learning cycle. Innovation demands rapid experiment-failure-success cycles. Someone identifies a problem or inefficiency in a product. Someone proposes a fix. The fix is tested and works or fails. We have learned something new. The faster this cycle happens, the faster and more accurately the project can move.

Indeed an "optimistic" perspective.  In reality it would more likely happen this way: new contributor gets code merged without review.  Busy maintainers, whose time is much more valuable than new contributors' time, spend their time cleaning up the mess made by someone who has yet to participate in the "learning cycle."  This is the antithesis of, "[To behave like a hacker, you have to believe that the thinking time of other hackers is precious — so much so that it's almost a moral duty for you to share information, solve problems and then give the solutions away just so other hackers can solve new problems instead of having to perpetually re-address old ones.](http://www.catb.org/esr/faqs/hacker-howto.html#believe2)" (Talk about understanding lessons of the past.)

> It gives outsiders the chance to troll the project. It is a simple as raising an objection to a new patch. "I don't like this code." Discussions over details can use up much more effort than writing code. It is far cheaper to attack a patch than to make one. These economics favor the trolls and punish the honest contributors.

Also preposterous.  Actual trolls should be ignored or banned.  As well, a completely false dichotomy.

> It puts the burden of work on individual contributors, which is ironic and sad for open source. We want to work together yet we're told to fix our work alone.

???  Nonsense.

Nothing there justifies "C4."

**Comment by Kodiologist** [comment] 2019-11-07 20:06
This isn't happening.

**Closed by Kodiologist** 2019-11-07 20:06 UTC
