### ISSUE TITLE
Defmacro doesn't capture helper function definitions

### ISSUE THREAD

**Issue by zhanghaze** [hylang/hy#1859] opened 2019-12-30 15:51 UTC
Sorry if this is a 

```
(defn mrest [x]
  (list (rest x))
  )
(defmacro ta [x]
  (setv yy (mrest x))
  `(print yy)
  )

(ta 'c)
```

 This macro will give error

`  NameError: name 'mrest' is not defined
`
So how can a macro call helper functions? does it have to be always inside of defmacro?

**Comment by brandonwillard** [comment] 2019-12-30 15:54
See [`eval-and-compile`](https://docs.hylang.org/en/stable/language/api.html#eval-and-compile) and/or [`eval-when-compile`](https://docs.hylang.org/en/stable/language/api.html#eval-when-compile).

**Comment by Kodiologist** [comment] 2019-12-30 15:55
Duplicate of #1414.

**Closed by Kodiologist** 2019-12-30 15:55 UTC
