### ISSUE TITLE
+ with zero arguments legal in some cases but not in others

### ISSUE THREAD

**Issue by Zabolekar** [hylang/hy#1232] opened 2017-02-23 17:56 UTC
In Hy, as in most other Lisps, `(+)` is legal and evaluates to `0`. Lets consider, however, the following function:

    (defn f [g] (g))

Then `(f +)` fails:

    Traceback (most recent call last):
      File "<input>", line 1, in <module>
      File "<input>", line 1, in f
      File "c:\users\zabolekar\appdata\local\programs\python\python36\lib\site-packages/hy/core/shadow.hy", line 34, in +
        (raise (TypeError "Need at least 1 argument to add/concatenate"))))
    TypeError: Need at least 1 argument to add/concatenate

The exception is not raised if we use a custom function instead:

    (defn my+ [&rest args]
      (reduce + args 0))
    
Then `(f my+)` evaluates to `0`, as it should.

Could be related to #647.

**Comment by Kodiologist** [comment] 2017-02-23 18:06
Duplicate of #1104. Thanks for reporting, anyway.

**Closed by Kodiologist** 2017-02-23 18:06 UTC
