### ISSUE TITLE
Do we *really* want setv to return a tuple?

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1049] opened 2016-04-16 03:02 UTC
Currently `setv` returns a tuple. Sometimes.

``` Hy
=> (print (setv x 7 y 42))
(7, 42)
=> (print (setv x 42))  ; shouldn't it print (42,)?
42
=> (print (setv x 7 x 42)  ; wouldn't you expect (7, 42)?
(42, 42)
```

I propose changing it to just return the value of the last assignment. This is more consistent with the way a single assignment works. If you assign to the same name more than once, it gets lost anyway, which is surprising. This is also more consistent with Common Lisp's `setq` which we've based `setv` on.

``` Lisp
* (setq x 42 x 42)
;; [dire warnings about using setq at toplevel]
42
*
```

It would also simplify my proposed `as->` macro. #1047 .

**Comment by shellhead** [comment] 2016-08-23 04:07
Is this a duplicate of #249 ?

**Comment by gilch** [comment] 2016-12-14 04:22
> It seems like the behavior may have changed since this was originally opened. 

@shellhead No, it's the opposite. `setv` has changed to allow multiple pairs from only one pair in the old PyPI version that you still seem to be using. Use the current github version for the new `setv`.

**Closed** 2017-03-24 04:38 UTC
