### ISSUE TITLE
Repl Bug

### ISSUE THREAD

**Issue by Arseny-N** [hylang/hy#982] opened 2015-10-26 21:16 UTC
Hi, nice project ! 

But if in the REPL  you type 
```   => (:)  ```
it crashes 
```
Traceback (most recent call last):
  File "/usr/bin/hy", line 9, in <module>
    load_entry_point('hy==0.11.0', 'console_scripts', 'hy')()
  File "/usr/lib/python2.7/site-packages/hy/cmdline.py", line 347, in hy_main
    sys.exit(cmdline_handler("hy", sys.argv))
  File "/usr/lib/python2.7/site-packages/hy/cmdline.py", line 342, in cmdline_handler
    return run_repl(spy=options.spy)
  File "/usr/lib/python2.7/site-packages/hy/cmdline.py", line 240, in run_repl
    os=platform.system()
  File "/usr/lib64/python2.7/code.py", line 243, in interact
    more = self.push(line)
  File "/usr/lib64/python2.7/code.py", line 265, in push
    more = self.runsource(source, self.filename)
  File "/usr/lib/python2.7/site-packages/hy/cmdline.py", line 113, in runsource
    sys.stderr.write(str(e))
  File "/usr/lib/python2.7/site-packages/hy/errors.py", line 104, in __str__
    self.message))
  File "/usr/lib/python2.7/site-packages/clint/textui/colored.py", line 108, in __radd__
    return str(other) + str(self.color_str)
UnicodeEncodeError: 'ascii' codec can't encode character u'\ufdd0' in position 24: ordinal not in range(128)
```
Here is the version
```
$ hy -v
hy 0.11.0
```

**Comment by gilch** [comment] 2015-10-26 21:58
I can confirm the error on master. It doesn't just throw an exception, but crashes the repl and kicks you back out into the shell. But only with Python2. It works fine using Python3:
```Hy
=> (:)
  File "<input>", line 1, column 1

  (:)
  ^-^
HyTypeError: `\ufdd0:' needs 1 arguments, got 0
```

**Comment by Scorpil** [comment] 2015-12-14 21:02
BTW, is there any reason to prefix keywords with \uFDD0? Couldn't find any please where it is actually useful.

**Comment by paultag** [comment] 2015-12-14 21:05
I really need to write up a copy paste explainer.

Yes. However, I want them to be real Objects. ':foo should be the same as
:foo in the resulting code.

Cheers,
  Paul

On Mon, Dec 14, 2015 at 4:02 PM, Andrew <notifications@github.com> wrote:

> BTW, is there any reason to prefix keywords with \uFDD0? Couldn't find any
> please where it is actually useful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hylang/hy/issues/982#issuecomment-164558487>.
>



-- 
:wq

**Comment by Scorpil** [comment] 2015-12-14 21:17
Comment would be useful, since I'm still not following :)
\uFDD0 is not character '. According to [this link](http://www.charbase.com/fdd0-unicode-invalid-character) it's actually unassigned. My terminal certainly can't print it...

**Comment by paultag** [comment] 2015-12-14 21:21
That's the intent -- it's a local use char.

This makes :foo != "foo" != foo

On Mon, Dec 14, 2015 at 4:17 PM, Andrew <notifications@github.com> wrote:

> Comment would be useful, since I'm still not following :)
> \uFDD0 is not character '. According to this link
> <http://www.charbase.com/fdd0-unicode-invalid-character> it's actually
> unassigned. My terminal certainly can't print it...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hylang/hy/issues/982#issuecomment-164562322>.
>



-- 
:wq

**Comment by Scorpil** [comment] 2015-12-14 21:31
Ah, got it. Thanks.

**Comment by berkerpeksag** [comment] 2015-12-14 21:58
https://github.com/hylang/hy/pull/999 has merged, closing this.

**Closed by berkerpeksag** 2015-12-14 21:58 UTC
Labels: bug
