### ISSUE TITLE
try-hylang is running old release of Hy

### ISSUE THREAD

**Issue by vodik** [hylang/hy#1563] opened 2018-04-01 20:34 UTC
I was showing it to a buddy, and noticed its running 0.13.

**Comment by Kodiologist** [comment] 2018-04-01 20:35
Duplicate of hylang/tryhy#6.

**Closed by Kodiologist** 2018-04-01 20:35 UTC

**Comment by vodik** [comment] 2018-04-01 21:13
Aaah, didn't realize its a different project. Sorry.
