### ISSUE TITLE
bytestrings

### ISSUE THREAD

**Issue by cwebber** [hylang/hy#732] opened 2014-12-27 21:20 UTC
There doesn't seem to be a nice way to do `b""` which is convenient in Hy and works on both py2 and py3 in the same way.

**Comment by Kodiologist** [comment] 2016-10-12 22:18
The `bytes` function doesn't really replace bytestring literals. For example, suppose you want `b"\xa0"`. As of Python 3.5, `(bytes "\xa0")` raises `TypeError` because of the lack of an encoding, and `(bytes "\xa0" "UTF-8")` produces `b"\xc2\xa0"`. So you actually need `(bytes [160])` or `(bytes [0xa0])`.

I played around a bit with trying to implement bytestring literals. The tricky part is that on Python 3, HyString inherits from `str` (and HySymbol inherits from HyString). We'll probably need to make HyString a bit more abstract so that it can represent both literal `bytes` objects and literal `str` objects (and continue to represent literal `unicode` objects under Python 2).

**Comment by Kodiologist** [comment] 2016-12-13 17:42
Whoops, this is a duplicate of #495.

**Closed by Kodiologist** 2016-12-13 17:42 UTC
Labels: good-first-bug, lisp-python-interop, new-syntax
