### ISSUE TITLE
Tracebacks are horribly, horribly broken in 0.10.1

### ISSUE THREAD

**Issue by rcarmo** [hylang/hy#727] opened 2014-12-21 11:43 UTC
There's something horribly broken in the traceback code in 0.10.1. When a runtime exception occurs, it invariably dumps an unrelated `TypeError` from `cmdline.hy`:

```python
Traceback (most recent call last):
  File "/Users/rcarmo/.pyenv/versions/2.7.8/bin/hy", line 9, in <module>
    load_entry_point('hy==0.10.1', 'console_scripts', 'hy')()
  File "/Users/rcarmo/.pyenv/versions/2.7.8/lib/python2.7/site-packages/hy/cmdline.py", line 305, in hy_main
    sys.exit(cmdline_handler("hy", sys.argv))
  File "/Users/rcarmo/.pyenv/versions/2.7.8/lib/python2.7/site-packages/hy/cmdline.py", line 296, in cmdline_handler
    (x.filename, x.errno, x.strerror))
TypeError: %d format: a number is required, not NoneType
```

This reproduces the issue every time for me:

```clojure
(import 
    [cookielib [CookieJar]]
    [cStringIO [StringIO]]
    [urllib2 [build-opener HTTPCookieProcessor]])

(defn get-page [url]
    (print "getting" url)
    (let [[jar    (CookieJar)]
          [opener (build-opener (HTTPCookieProcessor jar))]]
        (setv (. opener addheaders) [(, "User-agent" "Mozilla/5.0")])
        (.read (.open opener url))))

(defmain [&rest args]
    (print (get-page "http://nonexistent/")))
```

Looked like #714 at first, but if I wrap `(get-page)` with a parser function and that parser throws an exception, I get the same traceback. *sigh*

**Comment by berkerpeksag** [comment] 2015-02-06 07:16
This looks like a duplicate of #513.

**Closed by berkerpeksag** 2015-02-06 07:16 UTC
