### ISSUE TITLE
`setx` is scoped inconsistently in comprehension forms

### ISSUE THREAD

**Issue by scauligi** [hylang/hy#1994] opened 2021-03-15 03:06 UTC
Illustrative example:
```
=> (lfor x (range 3) (setx last x))
[0, 1, 2]
=> last
2
```
But:
```
=> (lfor x (range 3) :do (print x) (setx also-last x))
0
1
2
[0, 1, 2]
=> also-last
[...] NameError: name 'also_last' is not defined
```

This is because the former is compiled to
```python
[(last := x) for x in range(3)]
last  # same scope as assignment
```
whereas the latter is
```python
def _hy_anon_var_1():
    for x in range(3):
        print(x)
        yield (also_last := x)
[].__class__(_hy_anon_var_1())
also_last  # different scope from assignment
```

Generally, if the body of `lfor` (or `dfor` or `gfor`) is not a simple expression, then hy compiles it to an anonymous function. That means anything with a `:do` clause, any body with a `(do)` form, and probably many macros. However, this changes the scope of the body expression in unexpected ways.

I don't have a proposed solution for this, just pointing out that this happens and is weird.

**Comment by peaceamongworlds** [comment] 2021-03-15 08:25
I justified this to myself by saying that list comprehensions in Python have a separate internal scope. Hence things that happen within the `:do` clauses might not be seen outside of the comprehension.

However, 
```hy
=> (lfor x (range 3) (setx last x))
[(last := x) for x in range(3)]

[0 1 2]
=> 
```
this is weird. It seems to me to be more of an issue with Python's lack of block scope and things leaking through in unexpected ways sometimes.

**Comment by Kodiologist** [comment] 2021-03-15 16:39
It was always my intention that the comprehension forms be regarded as introducing a new function-level scope. The fact that a real comprehension statement, with no new scope, can be produced by Hy in some cases wasn't supposed to affect the user, because there formerly was no way to set variables in a Python comprehension other than the loop variables, which are scoped to the comprehension just as if it were a function. `setx` has thrown a wrench in the works. I guess the thing to do is to force the function-compilation mode when `setx` is used, although this would introduce a perhaps surprising inconsistency from Python. It was quite intentional on Python's part to leak `:=` assignments in comprehensions, and we'd be preventing that.

**Comment by scauligi** [comment] 2021-03-15 18:20
This affects more than just `setx`, though admittedly all edge-case why-are-you-doing-this cases. E.g. `(lfor x (locals) expr-vs-stmt)` will have different behavior depending on whether it's an expression or function context.

**Comment by allison-casey** [comment] 2021-03-15 22:12
could we get around this case by changing the anon function we make to a single arg function? as in:
```python
def _hy_anon_var_1(sym):
    print(sym)
    return sym

[(also_last := _hy_anon_var_1(x)) for x in range(3)]
```
this seems like it would cover the `(locals)` case as well. This would be a performance penalty though since we'd be calling a function every time. maybe only do this if we see a `setx` in tail position?

**Comment by scauligi** [comment] 2021-03-16 03:21
Another possible method would be, if we can capture all introduced variables (perhaps via introspection on the anon function?) we can expose them via `nonlocal` (or `global`, as the case may be), something like:

```
also_last : Any
def _hy_anon_var_1():
    nonlocal also_last
    for x in range(3):
        print(x)
        yield (also_last := x)
print(also_last)  # should work?
```

**Comment by allison-casey** [comment] 2021-03-16 16:27
oh interesting, we would also have to lift the iterable up out of the func  and into a gensym to cover the `(locals)` and `(globals)` cases. so maybe something like:
```python
also_last : Any
_gensym = locals()
def _hy_anon_var_1():
    nonlocal also_last
    for x in _gensym:
        print(x)
        yield (also_last := x)
[].__class__(_hy_anon_var_1())
print(also_last)  # should work?
```

**Comment by scauligi** [comment] 2021-03-16 21:26
Ah, I was thinking we would do the variable capture/detection in the compiler instead of at runtime; I think `ast` has methods to list the local variables in a function AST.

Yeah, we would have to detect whether we're in a top-level function or more nested to determine whether to use `nonlocal` vs `global`, but again this is something we should be able to do in the compiler (I think). Perhaps we could even expose this "auto-nonlocal" as a special form implementation for `nonlocal` (and make the original `nonlocal*`)?

**Comment by scauligi** [comment] 2021-03-17 05:43
Oh I totally misunderstood your point about gensymming `locals`, that's a really good catch.

Hmm, I don't really like having to special-case detecting a call to `locals`, it feels hacky... is there some way we could avoid having to create a temp function to begin with?

**Comment by allison-casey** [comment] 2021-03-17 17:35
I don't see a downside to lifting the iterable out of the fn and into a gensym every time :woman_shrugging:

**Comment by scauligi** [comment] 2021-03-17 17:42
The `(locals)` could be anywhere in the body, not necessarily just the iterable e.g.
```hy
(lfor x a-list (get (locals) (+ "_" x)))
```

**Comment by allison-casey** [comment] 2021-03-17 17:44
dang you're solutely right. I don't have a solution for that

**Comment by Kodiologist** [comment] 2021-09-09 19:17
Oh yes. This looks much more polished. Thanks for putting the time into it.

You've forbidden `global` and `nonlocal` in comprehension forms and in `let`. This is a regression; they seem to work fine on master. Can you fix it?

**Comment by allison-casey** [comment] 2021-12-22 17:09
was this closed in #2125? `setx` now works as expected

**Comment by Kodiologist** [comment] 2021-12-22 17:49
Did we remember to add a test?

**Comment by allison-casey** [comment] 2021-12-22 18:12
looks like it. There's tests in `comprehensions` and `py3_8_only_tests` that cover `setv` leakage and `setx` leaking respectively

**Comment by Kodiologist** [comment] 2021-12-22 18:12
Good enough for me.

**Closed by Kodiologist** 2021-12-22 18:12 UTC
Labels: complaint / disgust
