### ISSUE TITLE
Multiple runs of `hy <file.hy>` give different results

### ISSUE THREAD

**Issue by sleepyfox** [hylang/hy#1449] opened 2017-11-01 13:04 UTC
Using a simple test file:
```
(import unittest)
(defclass test-string-methods [unittest.TestCase]
  (defn test-upper [self]
    (self.assertEqual (.upper "foo") "FOO")))                                                                                                                                           
(unittest.main)
```
Running hy test.hy the first time gives me the following error output:
```
Traceback (most recent call last):
  File "/usr/local/bin/hy", line 11, in <module>
    load_entry_point('hy==0.13.0+141.ge0e8506', 'console_scripts', 'hy')()
  File "/usr/local/lib/python3.6/site-packages/hy/cmdline.py", line 346, in hy_main
    sys.exit(cmdline_handler("hy", sys.argv))
  File "/usr/local/lib/python3.6/site-packages/hy/cmdline.py", line 334, in cmdline_handler
    return run_file(options.args[0])
  File "/usr/local/lib/python3.6/site-packages/hy/cmdline.py", line 213, in run_file
    pretty_error(import_file_to_module, "__main__", filename)
  File "/usr/local/lib/python3.6/site-packages/hy/cmdline.py", line 186, in pretty_error
    return func(*args, **kw)
  File "/usr/local/lib/python3.6/site-packages/hy/importer.py", line 111, in import_file_to_module
    eval(code, module.__dict__)
  File "test.hy", line 8, in <module>
    (unittest.main)
  File "/usr/local/lib/python3.6/unittest/main.py", line 64, in __init__
    self.module = __import__(module)
ModuleNotFoundError: import of __main__ halted; None in sys.modules
```
But if I run `hy test.hy` a second time I get:
```
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
```
Subsequent runs work fine. If I delete `__pycache__` then the problem reappears. Using current hy from pip install:  0.13.0+141.ge0e8506

**Comment by kirbyfan64** [comment] 2017-11-01 14:31
Duplicate of #1134, which is probably one of the longer-standing nasty bugs tbh.

**Closed by kirbyfan64** 2017-11-01 14:31 UTC

**Comment by Kodiologist** [comment] 2017-11-01 14:34
@kirbyfan64 So what you're saying is, `unittest.main` imports its calling module, triggering #1134?

**Comment by kirbyfan64** [comment] 2017-11-01 14:35
Yup.

**Comment by sleepyfox** [comment] 2017-11-01 14:36
Can you please explain why this is a duplicate? Because to my (untutored) eye they appear different...

**Comment by sleepyfox** [comment] 2017-11-01 14:50
Is there a workaround to this, other than precompiling every .hy file to .py and calling `python -m unittest test_file`?

**Comment by sleepyfox** [comment] 2017-11-01 14:51
i.e. I'd like to be able to just work with hy files and do something like `hy -m unittest my_hy_test_file` (except that the previous doesn't work).

**Comment by Kodiologist** [comment] 2017-11-01 14:52
Why not use the more powerful and less verbose pytest? Hy's own conftest.py shows how to use pytest with Hy.

**Comment by sleepyfox** [comment] 2017-11-01 15:12
And I can do this without having to compile everything to .py files first?

**Comment by Kodiologist** [comment] 2017-11-01 15:13
Yes.
