### ISSUE TITLE
Inconsistent argument bracketing between `for`, `lfor`, and `loop`

### ISSUE THREAD

**Issue by peaceamongworlds** [hylang/hy#1941] opened 2021-01-22 12:07 UTC
`lfor`, and the other list comprehensions, take arguments as just consecutive forms, not in a list.
```hy
(lfor i (range 5) i)
```

`for` takes arguments with the same syntax as `lfor`, but in a list, same as `with` and `let`.
```hy
(for [i (range 5)] i)
```

`loop` takes a list of lists as arguments.
```hy
(loop [[i n] [acc 1]]
    (if (zero? i)
      acc
      (recur (dec i) (* acc i))))
```

Would it not make sense to make all of these consistent between themselves? I think that the best option would be to make all forms that require args to take a single even-length list like `for`.

**Comment by Kodiologist** [comment] 2021-01-22 12:54
Duplicate of #1723.

**Comment by Kodiologist** [comment] 2021-01-22 12:55
You can add a comment there about `loop` if you want, but see the discussion.

**Closed by Kodiologist** 2021-01-22 12:54 UTC
