### ISSUE TITLE
hy2py and internals

### ISSUE THREAD

**Issue by tmbdev** [hylang/hy#922] opened 2015-08-26 18:20 UTC
My impression was that hy2py should be able to convert arbitrary .hy files into .py files. However, it seems to fail when there is a definition for a builtin.

Regular 'hy' just seems to stick key/value pairs for strings like '+' into the module's dictionary, but hy2py does nothing equivalent. Import of such modules also seems to fail.

```
$  cat test.hy
(defn + [] 0)
$  hy2py test.hy
Traceback (most recent call last):
  File "/usr/local/bin/hy2py", line 9, in <module>
    load_entry_point('hy==0.11.0', 'console_scripts', 'hy2py')()
  File "/usr/local/lib/python2.7/dist-packages/hy/cmdline.py", line 408, in hy2py_main
    _ast = import_file_to_ast(options.args[0], module_name)
  File "/usr/local/lib/python2.7/dist-packages/hy/importer.py", line 67, in import_file_to_ast
    return hy_compile(import_file_to_hst(fpath), module_name)
  File "/usr/local/lib/python2.7/dist-packages/hy/compiler.py", line 2279, in hy_compile
    result = compiler.compile(tree)
  File "/usr/local/lib/python2.7/dist-packages/hy/compiler.py", line 428, in compile
    ret = self.compile_atom(_type, tree)
  File "/usr/local/lib/python2.7/dist-packages/hy/compiler.py", line 420, in compile_atom
    ret = _compile_table[atom_type](self, atom)
  File "/usr/local/lib/python2.7/dist-packages/hy/compiler.py", line 596, in compile_raw_list
    ret = self._compile_branch(entries)
  File "/usr/local/lib/python2.7/dist-packages/hy/compiler.py", line 483, in _compile_branch
    return _branch(self.compile(expr) for expr in exprs)
  File "/usr/local/lib/python2.7/dist-packages/hy/compiler.py", line 313, in _branch
    results = list(results)
  File "/usr/local/lib/python2.7/dist-packages/hy/compiler.py", line 483, in <genexpr>
    return _branch(self.compile(expr) for expr in exprs)
  File "/usr/local/lib/python2.7/dist-packages/hy/compiler.py", line 428, in compile
    ret = self.compile_atom(_type, tree)
  File "/usr/local/lib/python2.7/dist-packages/hy/compiler.py", line 420, in compile_atom
    ret = _compile_table[atom_type](self, atom)
  File "/usr/local/lib/python2.7/dist-packages/hy/compiler.py", line 1781, in compile_expression
    ret = self.compile_atom(fn, expression)
  File "/usr/local/lib/python2.7/dist-packages/hy/compiler.py", line 420, in compile_atom
    ret = _compile_table[atom_type](self, atom)
  File "/usr/local/lib/python2.7/dist-packages/hy/compiler.py", line 363, in checker
    return fn(self, expression)
  File "/usr/local/lib/python2.7/dist-packages/hy/compiler.py", line 1835, in compile_def_expression
    expression.start_column)
  File "/usr/local/lib/python2.7/dist-packages/hy/compiler.py", line 1843, in _compile_assign
    "Can't assign to a builtin: `%s'" % str_name)
hy.errors.HyTypeError:   File "None", line 1, column 7

HyTypeError: Can't assign to a builtin: `+'

$
```

**Comment by kirbyfan64** [comment] 2015-08-26 18:45
The error's the same in the REPL (although it's admittedly much prettier):

```
ryan@DevPC-LX:~$ hy
hy 0.11.0 using CPython(default) 2.7.6 on Linux
=> (defn + [] 0)
  File "<input>", line 1, column 7

  (defn + [] 0)
        ^^
HyTypeError: Can't assign to a builtin: `+'

=> 
ryan@DevPC-LX:~$ 
```

**Comment by tmbdev** [comment] 2015-08-26 18:49
In the toplevel, it kind of makes sense, though. However, in Hy, it seems to me that "test.+" should be definable.

**Comment by algernon** [comment] 2015-08-27 06:19
The problem is that `test.+` is still `+` as far as the `test` module is concerned, and thus, would shadow a built-in. Right now, the only way to define a function with the name of a built-in, is to use Hy from git master, and `(defclass)`.

**Comment by Foxboron** [comment] 2015-10-16 19:46
Closing this \o/

**Closed by Foxboron** 2015-10-16 19:46 UTC
