### ISSUE TITLE
what's wrong with (apply + [1 2 3])?

### ISSUE THREAD

**Issue by xificurC** [hylang/hy#1382] opened 2017-08-15 09:58 UTC
Apart from apply being deleted :) Are you planning a minor release soon?

```
λ hy --spy   
hy 0.13.0 using CPython(default) 3.5.2 on Linux
=> (apply + [1 2 3])
  File "<input>", line 1, column 8

  (apply + [1 2 3])
         ^^
HyTypeError: b"compiling the application of `+' didn't return a function call, but `Num'"
```

What I'm actually fighting with is writing `ap-cond`

```
(defmacro ap-cond [&rest clauses]
  (when clauses
    `(do (setv it ~(first (first clauses)))
         (if it
           ~@(cut (first clauses) 1)
           (apply ap-cond (cut clauses 1))))))
```
I used `cut` because `rest` was complaining

```
⤷ TypeError: Don't know how to wrap a <class 'itertools.islice'> object to a HyObject
```

But I'm still getting owned

```
(ap-cond [(> 2 3) :foo] [(> 3 2) it])
  File "<input>", line 1, column 1

  (ap-cond [(> 2 3) :foo] [(> 3 2) it])
  ^-----------------------------------^
HyTypeError: b"compiling the application of `ap_cond' didn't return a function call, but `Name'"
```

**Comment by xificurC** [comment] 2017-08-15 13:20
Discussion on IRC landed that this works

```
(apply hy.core.shadow.+ [1 2 3])
```

Up to discussion whether this is a bug or a feature :)

**Comment by Kodiologist** [comment] 2017-08-15 14:19
Duplicate of #647, which is in fact fixed, but bugs don't get fixed in old releases.

> Are you planning a minor release soon?

I'm not, no. I think twice a year is a good schedule, so I'm aiming to release 0.14.0 in January.

**Closed by Kodiologist** 2017-08-15 14:19 UTC

**Comment by xificurC** [comment] 2017-08-15 20:41
> I think twice a year is a good schedule, so I'm aiming to release 0.14.0 in January.

too bad, with the lively development I could even take monthly. Thanks for the quick response!

**Comment by Kodiologist** [comment] 2017-08-15 21:24
If you want the bleeding edge, why not install from master? That's what all the cool kids (i.e. me) do.

**Comment by xificurC** [comment] 2017-08-15 21:30
I'm using hy in some company scripts, I can't just reference master blindly :)

**Comment by Kodiologist** [comment] 2017-08-15 21:31
True, but you can refer to a particular Git commit. Then, pull and upgrade whenever you're ready.

**Comment by xificurC** [comment] 2017-08-15 21:32
I'll have to read up on that. Thanks
