### ISSUE TITLE
[hy version 0.13.0] macro import error causes module with imported macros output incorrect compiled byte code

### ISSUE THREAD

**Issue by pyx** [hylang/hy#1316] opened 2017-07-03 09:47 UTC
Hy version 0.13.0

Given:

a.hy:
```clojure
(defmacro m [] `(print 'macro-m))
```

b.hy:
```clojure
(require [a [m]])
```

Then:

```clojure
(require [b [m]])
(m)
```
works, prints out `macro-m`, and then complied byte code for both `a.hy` and `b.hy` been saved in `__pycache__` directory.

If, instead, we run code that fails first (that is, there is no existing compiled byte code, or after `rm -r __pycache__`), for example, run this first:
```clojure
(require [b [non-exist]])
```
from then on,
```clojure
(require [b [m]])
```
will fail as long as the compiled byte code file (that built by the failed `require` call) exists.

For local script, removing the cached byte code file, such as `rm -f __pycache__` will fix it temporary, for installed modules (in site-packages, and in virtual envs), there is no user-friendly way to fix that.

I am guessing (since I did not read the relevant part of the code), by not saving compiled byte code if the code fail, will fix this.

**Comment by Kodiologist** [comment] 2017-07-03 14:38
Confirmed:

    $ echo '(defmacro m [] `(print `macro-m))' > a.hy
    $ echo '(require [a [m]])' > b.hy
    $ hy -c '(require [b [m]])'
    $ hy -c '(require [b [non-exist]])'
    … ImportError: cannot require names: ['non_exist'] …
    $ hy -c '(require [b [m]])'
    … ImportError: cannot require names: [m] …

It's a weird one, too. Thanks for reporting.

**Comment by Kodiologist** [comment] 2017-07-03 21:45
Wait a minute, I get it now. The problem isn't trying to require a macro that doesn't exist. The problem is trying to require a macro that isn't loaded when the bytecode is loaded. `(require [b [m]])` works when `b.hy` hasn't been byte-compiled yet, but doesn't once it has:

    $ echo '(defmacro m [] `(print `macro-m))' > a.hy
    $ echo '(require [a [m]])' > b.hy
    $ hy -c '(require [b [m]])'
    $ hy -c '(require [b [m]])'
    … ImportError: cannot require names: [m] …

So this is a duplicate of #1268, although it shows that the problem of `require` not compiling to anything has worse consequences than for `eval`.

**Closed by Kodiologist** 2017-07-03 21:45 UTC
Labels: bug

**Comment by pyx** [comment] 2017-07-03 23:08
@Kodiologist thanks, so the cause should be there is no 'compiled bytecode for macro' (whatever that means) in .pyc files.  Do not generate byte code file for any .hy source with macro definition, maybe?

IMHO, This is a showstopper.

**Comment by Kodiologist** [comment] 2017-07-03 23:45
It's not that bad, and there's an easy workaround: require each macro you want from the module in which it's defined (`a`, in this case) rather than a module that itself gets the macro with `require` (`b`, in this case). `defmacro` compiles to something; it's `require` that's more troublesome.

**Comment by pyx** [comment] 2017-07-04 00:22
@Kodiologist it depends, for example, to have easier to remember interface, a package with many public macros, can have all those macros being aggregated into a module, namely 'some_package.macros'.  (I encountered this situation in https://github.com/pyx/hymn .

This issue prevents that.
