### ISSUE TITLE
Crash with broken macro: AttributeError: 'HyExpression' object has no attribute 'start_line'

### ISSUE THREAD

**Issue by hrehfeld** [hylang/hy#1278] opened 2017-04-16 14:23 UTC
https://gist.github.com/hrehfeld/075ea02c5bd9de157d7f12fc698755c4

**Comment by Kodiologist** [comment] 2017-04-16 14:39
This seems to be a duplicate of #818.

**Closed by Kodiologist** 2017-04-16 14:39 UTC

**Comment by hrehfeld** [comment] 2017-04-16 14:43
Ah, sorry!

**Comment by Kodiologist** [comment] 2017-04-16 14:44
No problem; finding duplicates is often difficult.
