### ISSUE TITLE
import does not work as in python

### ISSUE THREAD

**Issue by pyx** [hylang/hy#1633] opened 2018-06-07 23:24 UTC
I've created a demo package here:
https://github.com/pyx/hy-issue-1633

clone and run `make`

```
$ make
python test.py
--- from python ---
py func relative import
py func absolute import
hy test_py.hy
--- from hy ---
py func relative import
py func absolute import
hy test.hy
--- from hy ---
Traceback (most recent call last):
  File "/home/pyx/.virtualenvs/ri/bin/hy", line 11, in <module>
    load_entry_point('hy', 'console_scripts', 'hy')()
  File "/home/pyx/projects/hy/hy/cmdline.py", line 363, in hy_main
    sys.exit(cmdline_handler("hy", sys.argv))
  File "/home/pyx/projects/hy/hy/cmdline.py", line 351, in cmdline_handler
    return run_file(options.args[0])
  File "/home/pyx/projects/hy/hy/cmdline.py", line 224, in run_file
    pretty_error(import_file_to_module, "__main__", filename)
  File "/home/pyx/projects/hy/hy/cmdline.py", line 197, in pretty_error
    return func(*args, **kw)
  File "/home/pyx/projects/hy/hy/importer.py", line 96, in import_file_to_module
    load_module(module_name))
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 262, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "test.hy", line 3, in <module>
    (import [ri_hy [func]])
  File "/home/pyx/projects/hy/hy/importer.py", line 244, in load_module
    return import_file_to_module(fullname, self.path, self)
  File "/home/pyx/projects/hy/hy/importer.py", line 96, in import_file_to_module
    load_module(module_name))
  File "/home/pyx/projects/ri/ri_hy/__init__.hy", line 1, in <module>
    (import [.mod [func]])
ImportError: attempted relative import with no known parent package
make: *** [Makefile:4: all] Error 1
```

What's happening here is, even the package structure is the same, hy code translate directly from python does not work on both absolute import and relative import from hy package.

**Comment by pyx** [comment] 2018-06-07 23:31
And the stack traceback of trying absolute import (not shown above)
```
Traceback (most recent call last):
  File "/home/pyx/.virtualenvs/ri/bin/hy", line 11, in <module>
    load_entry_point('hy', 'console_scripts', 'hy')()
  File "/home/pyx/projects/hy/hy/cmdline.py", line 363, in hy_main
    sys.exit(cmdline_handler("hy", sys.argv))
  File "/home/pyx/projects/hy/hy/cmdline.py", line 351, in cmdline_handler
    return run_file(options.args[0])
  File "/home/pyx/projects/hy/hy/cmdline.py", line 224, in run_file
    pretty_error(import_file_to_module, "__main__", filename)
  File "/home/pyx/projects/hy/hy/cmdline.py", line 197, in pretty_error
    return func(*args, **kw)
  File "/home/pyx/projects/hy/hy/importer.py", line 116, in import_file_to_module
    eval(code, module.__dict__)
  File "test.hy", line 4, in <module>
    (import [ai_hy [func]])
  File "/home/pyx/projects/hy/hy/importer.py", line 244, in load_module
    return import_file_to_module(fullname, self.path, self)
  File "/home/pyx/projects/hy/hy/importer.py", line 96, in import_file_to_module
    load_module(module_name))
  File "/home/pyx/projects/ri/ai_hy/__init__.hy", line 1, in <module>
    (import [ai_hy.mod [func]])
ModuleNotFoundError: No module named 'ai_hy.mod'; 'ai_hy' is not a package
make: *** [Makefile:4: all] Error 1
```

**Comment by Kodiologist** [comment] 2018-06-08 01:59
This looks like a duplicate of #1134.

**Closed by Kodiologist** 2018-06-08 01:59 UTC

**Comment by pyx** [comment] 2018-06-08 02:28
@Kodiologist 

I added a new test case to the repos.

In this test, `test_2.hy`, no content in `__init__.hy` and no self/circular importing, just one of the module imports from the other via relative import. Do you think that's related?

**Comment by pyx** [comment] 2018-06-08 02:33
@Kodiologist never mind. I misread the error message, it worked. Sorry about that.
