### ISSUE TITLE
Is support for clojure like destructuing considered ?

### ISSUE THREAD

**Issue by max-l** [hylang/hy#1937] opened 2021-01-10 16:23 UTC
I was very much thrilled to discover this project, I'm working on a project that has to be in Python, and the expressive power of a lisp like language with macros would be very valuable. 

I am puzzled as to why there is not support for destructuring such as:

  https://clojure.org/guides/destructuring

I saw that this destructuing module was once considered for addition: 

  https://github.com/hylang/hy/pull/1328

but it hasn't been added. 

Is support for clojure like destructuing considered ?

**Comment by Kodiologist** [comment] 2021-01-10 16:25
Duplicate of #1936, I think. I don't know of anybody who's working on this right now, no.

**Closed by Kodiologist** 2021-01-10 16:25 UTC
