### ISSUE TITLE
`importlib.reload` not works for hy module

### ISSUE THREAD

**Issue by minghu6** [hylang/hy#1480] opened 2018-01-04 14:00 UTC
I test it on `hy` REPL and script, found that can't reload changes.
the test script are as follow:

```python
def test_reload_hy_module():
    import os
    import tempfile
    import logging

    temp_module_name = next(tempfile._get_candidate_names())
    tempfile_name = temp_module_name + '.hy'

    with open(tempfile_name, 'w') as fw:
        fw.write('(setv *constant-var* "constant") (defn t [n] (+ n 1))')

    temp_module = importlib.import_module(temp_module_name)
    origin_constant = getattr(temp_module, 'CONSTANT_VAR')
    origin_t = getattr(temp_module, 't')

    with open(tempfile_name, 'w') as fw:
        fw.write('(setv *constant-var* "constant-reload") (defn t [n] (+ n 2))')

    temp_module = importlib.reload(temp_module)
    reload_constant = getattr(temp_module, 'CONSTANT_VAR')
    reload_t = getattr(temp_module, 't')

    try:
        assert origin_constant != reload_constant
        assert origin_t(1) != reload_t(1)
    except AssertionError as ex:
        logging.exception(ex)
    finally:
        os.remove(tempfile_name)


if __name__ == '__main__':
    #reload_python()
    test_reload_hy_module()

```

**Comment by Kodiologist** [comment] 2018-01-04 15:23
Duplicate of #712. Don't forget to check for duplicates before submitting an issue.

**Closed by Kodiologist** 2018-01-04 15:23 UTC
