### ISSUE TITLE
macroexpand can crash the repl

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1413] opened 2017-09-05 05:21 UTC
Possibly related to #1412 
```Python
=> (defmacro bad [] (/ 0))
import hy
hy.macros.macro('bad')((lambda : (1 / 0)))
<function <lambda> at 0x000002594F390D08>
=> (bad)
  File "<input>", line 1, column 1

  (bad)
  ^---^
HyMacroExpansionError: b"expanding `bad': ZeroDivisionError('division by zero',)"


=> (macroexpand '(bad))
from hy.core.language import macroexpand
from hy import HyExpression, HySymbol
macroexpand(HyExpression(([] + [HySymbol('bad')])))
Traceback (most recent call last):
  File "c:\users\me\documents\github\hy\hy\macros.py", line 199, in macroexpand_1
    obj = m(*ntree[1:], **opts)
  File "<eval>", line 1, in <lambda>
ZeroDivisionError: division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\me\documents\github\hy\hy\cmdline.py", line 99, in runsource
    ast_callback)
  File "c:\users\me\documents\github\hy\hy\importer.py", line 201, in hy_eval
    return eval(ast_compile(expr, "<eval>", "eval"), namespace)
  File "<eval>", line 1, in <module>
  File "c:\users\me\documents\github\hy/hy/core/language.hy", line 313, in macroexpand
    (hy.macros.macroexpand form (HyASTCompiler name)))
  File "c:\users\me\documents\github\hy\hy\macros.py", line 163, in macroexpand
    tree = macroexpand_1(tree, compiler)
  File "c:\users\me\documents\github\hy\hy\macros.py", line 206, in macroexpand_1
    raise HyMacroExpansionError(tree, msg)
hy.errors.HyMacroExpansionError: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ME\Envs\gilch-hy36\Scripts\hy-script.py", line 11, in <module>
    load_entry_point('hy', 'console_scripts', 'hy')()
  File "c:\users\me\documents\github\hy\hy\cmdline.py", line 346, in hy_main
    sys.exit(cmdline_handler("hy", sys.argv))
  File "c:\users\me\documents\github\hy\hy\cmdline.py", line 341, in cmdline_handler
    return run_repl(spy=options.spy, output_fn=options.repl_output_fn)
  File "c:\users\me\documents\github\hy\hy\cmdline.py", line 236, in run_repl
    os=platform.system()
  File "c:\users\me\appdata\local\programs\python\python36\Lib\code.py", line 233, in interact
    more = self.push(line)
  File "c:\users\me\appdata\local\programs\python\python36\Lib\code.py", line 259, in push
    more = self.runsource(source, self.filename)
  File "c:\users\me\documents\github\hy\hy\cmdline.py", line 105, in runsource
    print(e, file=sys.stderr)
  File "c:\users\me\documents\github\hy\hy\errors.py", line 46, in __str__
    line = self.expression.start_line
AttributeError: 'HyExpression' object has no attribute 'start_line'

Process inferior-lisp exited abnormally with code 1
```

**Comment by Kodiologist** [comment] 2017-09-05 05:40
Looks like a duplicate of #818.

**Comment by gilch** [comment] 2017-09-05 05:54
Related, yes. Perhaps fixing that would fix this too, but the repl isn't even mentioned in that issue.

**Comment by Kodiologist** [comment] 2017-09-05 14:21
Any exception raised while printing an exception will crash the REPL, because the REPL tries to show the user the exception.

**Comment by gilch** [comment] 2017-09-05 20:03
The REPL should catch exceptions raised while printing things, even other exceptions. See how Python handles a similar problem?
```Python
>>> class BadException(Exception):
	def __str__(self):
		1 / 0

		
>>> raise BadException
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    raise BadException
BadException: <unprintable BadException object>
```
Each of the "read" "eval" and "print" steps must catch exceptions and print an appropriate error. The repl should *never* terminate due to an exception.

**Comment by Kodiologist** [comment] 2017-09-05 21:23
I don't disagree. But it seems that that's your bug of interest. Beyond that, this seems to be a duplicate of #818, and #1412 seems not to be a bug (you're not supposed to use `macro-error` like that). So I say you should close one and retitle the other.

**Comment by Kodiologist** [comment] 2017-09-08 18:29
@gilch Would you object if I did that?

**Comment by Kodiologist** [comment] 2017-09-09 15:49
Minimal example: `(raise (type "x" (, BaseException) {"__str__" (fn [self] (/ 0))}))` crashes the REPL with `__console__.x: <exception str() failed>`. The bug is probably catching `Exception` instead of `BaseException` [here](https://github.com/hylang/hy/blob/51fb807cc9eb5b005b79b4dbe819d8e11889de78/hy/cmdline.py#L109).

**Closed** 2017-09-12 02:19 UTC
Labels: bug
