### ISSUE TITLE
Syntax / macros for slices in numpy/pandas/etc.

### ISSUE THREAD

**Issue by asemic-horizon** [hylang/hy#1818] opened 2019-09-08 19:04 UTC
I'm doing a Kaggle contest this weekend and noting a couple of patterns in typical EDA Python work that are awkward in Hy.  

1) Multidimensional slicing like `X[i,j]`, `X[a:b,j]`, `X[i,:]`. 
2) Conditional slices like X[X.type == "N"]
3) Chained slices like X[X.type == "N"]["value"]

The latter, for example, looks like 
````
 (get (get X (= (get X "type") "N")) "value"))
````

Can we consider this a feature request? It takes learning *some* numpy to figure out what are the explicit functions behind the syntax sugar, so it  may not get done in any foreseeable future -- but it's a common Python use case and thus a major selling point for Hy.

**Comment by Kodiologist** [comment] 2019-09-08 20:08
Duplicate of #541.

**Closed by Kodiologist** 2019-09-08 20:08 UTC
